version: '2'
services:
  core-proxy:
    image: pysysops/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
    environment:
      - PROXY_KEY=whoami.core
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami-blue-proxy:
    image: pysysops/nginx-proxy
    container_name: blue-proxy
    environment:
      - PROXY_KEY=whoami.blue
      - APP_KEY=whoami.core
      - VIRTUAL_HOST=whoami.local
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - APP_KEY=whoami.blue
      - VIRTUAL_HOST=whoami.local
